#!/usr/bin/env python3
"""Regenerate every launcher-icon asset from design/logo/rommdroid-icon.svg.

Emits:
  app/src/main/res/drawable/ic_launcher_background.xml   adaptive background layer
  app/src/main/res/drawable/ic_launcher_foreground.xml   adaptive foreground layer
  app/src/main/res/drawable/ic_launcher_monochrome.xml   themed-icon layer (API 33+)
  app/src/main/res/mipmap-*/ic_launcher.png              legacy square icon
  app/src/main/res/mipmap-*/ic_launcher_round.png        legacy round icon
  design/logo/rommdroid-play-512.png                     Play Store listing icon

Needs `resvg` on PATH for the PNGs (falls back to `nix-shell -p resvg`).
The vector drawables are emitted without it.
"""
import copy
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SVG = "http://www.w3.org/2000/svg"
ROOT = Path(__file__).resolve().parents[2]
MASTER = ROOT / "design/logo/rommdroid-icon.svg"
RES = ROOT / "app/src/main/res"

# The master canvas maps onto the adaptive icon's 72dp safe zone, so the art
# survives every launcher mask. 108dp viewport = 768 units, art inset by 128.
CANVAS, VIEWPORT, INSET = 512, 768, 128
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}


def num(v):
    f = float(v)
    return f"{f:g}"


def rrect_path(x, y, w, h, r):
    """Rounded rect as VectorDrawable-safe path data (no rx attribute there)."""
    x, y, w, h, r = (float(v) for v in (x, y, w, h, r))
    r = min(r, w / 2, h / 2)
    hx, vy = w - 2 * r, h - 2 * r
    return (
        f"M{num(x + r)},{num(y)} h{num(hx)} a{num(r)},{num(r)} 0 0 1 {num(r)},{num(r)} "
        f"v{num(vy)} a{num(r)},{num(r)} 0 0 1 -{num(r)},{num(r)} h-{num(hx)} "
        f"a{num(r)},{num(r)} 0 0 1 -{num(r)},-{num(r)} v-{num(vy)} "
        f"a{num(r)},{num(r)} 0 0 1 {num(r)},-{num(r)} z"
    )


def shapes(el, inherited_fill=None):
    """Flatten an SVG element into [(role, path_data, fill)], document order."""
    out = []
    for child in el:
        tag = child.tag.split("}")[-1]
        role = child.get("data-role") or el.get("data-role")
        fill = child.get("fill") or inherited_fill
        if tag == "g":
            out += shapes(child, fill)
        elif tag == "rect":
            out.append((role, rrect_path(child.get("x", 0), child.get("y", 0),
                                         child.get("width"), child.get("height"),
                                         child.get("rx", 0)), fill))
        elif tag == "path":
            out.append((role, child.get("d"), fill))
    return out


def vector(body, indent="  "):
    ns = 'xmlns:android="http://schemas.android.com/apk/res/android"'
    return (
        f'<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- Generated by design/logo/generate-icons.py - do not edit. -->\n'
        f'<vector {ns}\n'
        f'    android:width="108dp"\n'
        f'    android:height="108dp"\n'
        f'    android:viewportWidth="{VIEWPORT}"\n'
        f'    android:viewportHeight="{VIEWPORT}">\n'
        f'{body}\n'
        f'</vector>\n'
    )


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  {path.relative_to(ROOT)}")


def resvg(svg_path, png_path, size):
    exe = shutil.which("resvg")
    cmd = ([exe] if exe else ["nix-shell", "-p", "resvg", "--run",
                              f"resvg --width {size} --height {size} '{svg_path}' '{png_path}'"])
    if exe:
        cmd += ["--width", str(size), "--height", str(size), str(svg_path), str(png_path)]
    subprocess.run(cmd, check=True, capture_output=True)


def main():
    ET.register_namespace("", SVG)
    tree = ET.parse(MASTER)
    root = tree.getroot()
    flat = shapes(root)
    bg = next(s for s in flat if s[0] == "bg")
    fg = [s for s in flat if s[0] not in (None, "bg")]

    grad = root.find(f"{{{SVG}}}defs/{{{SVG}}}linearGradient")
    stops = [(s.get("offset"), s.get("stop-color")) for s in grad]

    print("vector drawables:")
    items = "\n".join(
        f'                <item android:offset="{o}" android:color="{c}"/>' for o, c in stops)
    write(RES / "drawable/ic_launcher_background.xml", vector(
        f'    <path android:pathData="M0,0h{VIEWPORT}v{VIEWPORT}h-{VIEWPORT}z">\n'
        f'        <aapt:attr xmlns:aapt="http://schemas.android.com/aapt"\n'
        f'                   name="android:fillColor">\n'
        f'            <gradient\n'
        f'                android:type="linear"\n'
        f'                android:startX="{INSET}" android:startY="{INSET}"\n'
        f'                android:endX="{VIEWPORT - INSET}" android:endY="{VIEWPORT - INSET}">\n'
        f'{items}\n'
        f'            </gradient>\n'
        f'        </aapt:attr>\n'
        f'    </path>'))

    paths = "\n".join(
        f'        <path\n'
        f'            android:pathData="{d}"\n'
        f'            android:fillColor="{f}"/>' for _, d, f in fg)
    write(RES / "drawable/ic_launcher_foreground.xml", vector(
        f'    <group android:translateX="{INSET}" android:translateY="{INSET}">\n'
        f'{paths}\n'
        f'    </group>'))

    # Themed icons are a single tinted silhouette: cartridge shell with the
    # arrow and the connector pins punched out via even-odd winding.
    solid = " ".join(d for role, d, _ in fg if role in ("body", "arrow", "pins"))
    write(RES / "drawable/ic_launcher_monochrome.xml", vector(
        f'    <group android:translateX="{INSET}" android:translateY="{INSET}">\n'
        f'        <path\n'
        f'            android:pathData="{solid}"\n'
        f'            android:fillType="evenOdd"\n'
        f'            android:fillColor="#FFFFFF"/>\n'
        f'    </group>'))

    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n'
                '<!-- Generated by design/logo/generate-icons.py - do not edit. -->\n'
                '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@drawable/ic_launcher_background"/>\n'
                '    <foreground android:drawable="@drawable/ic_launcher_foreground"/>\n'
                '    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>\n'
                '</adaptive-icon>\n')
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        write(RES / "mipmap-anydpi-v26" / name, adaptive)

    # Raster fallbacks. The backdrop's corner radius is the only difference
    # between the square, round and Play Store cuts.
    backdrop = root.find(f'.//{{{SVG}}}rect[@data-role="bg"]')
    tmp = MASTER.parent / ".tmp-render.svg"
    print("raster icons:")
    try:
        for suffix, radius in (("", 114), ("_round", CANVAS // 2)):
            backdrop.set("rx", str(radius))
            tree.write(tmp)
            for density, px in DENSITIES.items():
                out = RES / f"mipmap-{density}/ic_launcher{suffix}.png"
                resvg(tmp, out, px)
                print(f"  {out.relative_to(ROOT)} ({px}px)")
        backdrop.set("rx", "0")  # Play applies its own mask
        tree.write(tmp)
        play = MASTER.parent / "rommdroid-play-512.png"
        resvg(tmp, play, 512)
        print(f"  {play.relative_to(ROOT)} (512px)")
    except FileNotFoundError:
        sys.exit("resvg not found; install it or run inside `nix develop`")
    finally:
        tmp.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
